### ISSUE TITLE
Disconnecting Bot 

### ISSUE THREAD

**Issue by Felixtrem** [JadeMin/aternos-afkbot#11]
The bot disconnects after a few seconds, but only when no one is on the world with him. 
The error is: Invalid move player packet received
I have no mods on my aternos server and only Skin Resorer Plugin
How can I solve this problem?
Please help me, thank you in advance!

**Comment by JadeMin** [comment]
Solution on https://github.com/JadeMin/aternos-afkbot/issues/10#issuecomment-1439495650.
