### ISSUE TITLE
Cannot join bot at replit server

### ISSUE THREAD

**Issue by Miku21750** [JadeMin/aternos-afkbot#13]
I follow all of your step until no. 9 . but when i click join bot, it show a message 
`connect ECONNREFUSED 185.107.194.19:40458`

this is the config.json 
`{
	"client": {
		"host": "Miku2120.aternos.me",
		"port": "40458",
		"username": "AFK_Miku21Bot"
	},
	
	"! DO NOT EDIT BELOW !": "ONLY IF YOU KNOW WHAT YOU'RE DOING",
	"logLevel": ["error", "log", "debug"],
	"action": {
		"commands": ["forward", "back", "left", "right", "jump"],
		"holdDelays": [1000, 2000, 3000, 4000, 5000, 6000],
		"retryDelay": 15000
	}
}`

EDIT :
I Forget to see the terminal and this what i get

` AFKBot got an error: Error: connect ECONNREFUSED 185.107.194.19:40458
[Error: connect ECONNREFUSED 185.107.194.19:40458] {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '185.107.194.19',
  port: 40458
}`

sorry for my bad english

**Comment by Miku21750** [comment]
Nope, i am pretty sure the host and port are not have any typo

Below is the screenshot of my server
![Screenshot_2023-04-03-19-37-04-78](https://user-images.githubusercontent.com/99104875/229511695-ed9187a8-c0d3-4404-b1ba-9bf6dd2a54d7.jpg)

**Comment by BannedPlayer** [comment]
I didn't understand how it was done. Can you make a video on how to use it?
