### ISSUE TITLE
ERROR connect ENOENT Please enter your server port

### ISSUE THREAD

**Issue by Ppandpoopoo2134** [JadeMin/aternos-afkbot#14]
Hey, I made it up to step 9 but when I click 'join bot' it keeps popping up 

ERROR
connect ENOENT Please enter your server port

I have my server port but where do I put it??

**Comment by Ppandpoopoo2134** [comment]
Update; figured it out, however now I'm getting this error

AFKBot got an error: Error: ETIMEDOUT

**Comment by JadeMin** [comment]
Hello, `ETIMEDOUT` usually means the bot cannot reach your server so the connection has been timed out.
Check your host and port has typos.
