### ISSUE TITLE
webview login not working

### ISSUE THREAD

**Issue by nekiontop** [JadeMin/aternos-afkbot#17]
so if i run the whole progress n stuff the webview shows up, after i copied the url and visited the website i put my password in the `secret´and it kept saying password incorrect over and over again, i put my password into key and value just some numbers.

**Comment by JadeMin** [comment]
see the password logs like ``YOUR PASSWORD: SOMETHING` in the Repl and

**Comment by nekiontop** [comment]
> Go to your Repl project and check the password logs like `your PASSWORD: SOMETHING`, `requested PASSWORD: SOMETHING`

have you got discord by any chance? i hope i could show it you there.

**Comment by JadeMin** [comment]
![image](https://user-images.githubusercontent.com/36400787/235449690-06b711fa-903c-446a-be22-3c8cabf83539.png)
Literally. https://discord.gg/44WtDkgxyk
