### ISSUE TITLE
Gettin some errors

### ISSUE THREAD

**Issue by ElCunq** [JadeMin/aternos-afkbot#19]
Error: getaddrinfo EAI_AGAIN "IP"
    at __node_internal_captureLargerStackTrace (node:internal/errors:478:5)
    at __node_internal_ (node:internal/errors:700:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'IP'

I couldn't find how to solve it. It just started randomly.

**Comment by JadeMin** [comment]
Put your server url to `host` in `config.json`.

Like this
```json
"client": {
    "host": "minecraft.aternos.me",
    "port": "25565",
    "username": "my afkbot"
}
```

**Comment by ElCunq** [comment]
everything was normal it suddenly gave the error. But suddenly it started to work again. But thanks for help.

**Comment by JadeMin** [comment]
It seems there was an issue with the hosting provider (Repl.it).
