### ISSUE TITLE
error when i press run

### ISSUE THREAD

**Issue by FelipeFMA** [JadeMin/aternos-afkbot#8]
Error: Cannot find module '/home/runner/aternos-afkbot/index.js'
Require stack:
- /nix/store/29fdcv1yhlll61ml8a31qdkrbprxd7gs-prybar-nodejs-0.0.0-67f7a00/prybar_assets/nodejs/module-context-hook.js
- /tmp/prybar-nodejs-466664332.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.resolve (node:internal/modules/cjs/helpers:109:19)

**Comment by JadeMin** [comment]
fixed on [339632e](https://github.com/JadeMin/aternos-afkbot/commit/339632ef273d7c47709d1908c7ee54857dfffea3)

If you want to update without losing your files (like `config.json`)
1. Go to your `aternos-afkbot` REPL project
2. Click `Git` in the left `Tools` section
3. Click the orange `Pull` button
4. If you see what you want to keep something whatever version then select on `Keep Replit version` and continue.

**Comment by Qaveru** [comment]
I made a clear install from your repo but it still has the same error

Error: Cannot find module '/home/runner/aternos-afkbot/index.js'
Require stack:
- /nix/store/29fdcv1yhlll61ml8a31qdkrbprxd7gs-prybar-nodejs-0.0.0-67f7a00/prybar_assets/nodejs/module-context-hook.js
- /tmp/prybar-nodejs-4267314059.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.resolve (node:internal/modules/cjs/helpers:109:19)

**Comment by JadeMin** [comment]
# final fixed on [2ba588c](https://github.com/JadeMin/aternos-afkbot/commit/2ba588cef5dc7c77d26b38baec9b9d113c7fb5a0)!
### You can update by forking again from the step 8 in [Setup](https://github.com/JadeMin/aternos-afkbot#setup-).
### Or if you wanna update without losing your config files
1. Go to your `aternos-afkbot` REPL project and enter the editor
2. Click `Git` in the left `Tools` section
3. Click the orange `Pull` button
4. If you see something like "you wanna keep (...)?"
then select on Replit thing to be not overwritten yours and continue.

**Comment by JadeMin** [comment]
# final fixed on [2ba588c](https://github.com/JadeMin/aternos-afkbot/commit/2ba588cef5dc7c77d26b38baec9b9d113c7fb5a0)!
### Please update by setup again from the step 8 in [Setup](https://github.com/JadeMin/aternos-afkbot#setup-).

**Comment by JadeMin** [comment]
# final fixed on [36fe401](https://github.com/JadeMin/aternos-afkbot/commit/36fe4017c440fe374c0475797d7c8130ed52aeb1)!
### Please update by setup again from the step 8 in [Setup](https://github.com/JadeMin/aternos-afkbot#setup-).
