### ISSUE TITLE
just nothing on the dashboard

### ISSUE THREAD

**Issue by Qaveru** [JadeMin/aternos-afkbot#9]
script is loading ok but after opening dashboard on the link, theres just nothing appears, only white background

**Comment by JadeMin** [comment]
can't reproduce. did you open it in new tab?

**Comment by Qaveru** [comment]
yes

**Comment by Qaveru** [comment]
https://aternos-afkbot.judokampd.repl.co/dashboard/ here's link if you want to see it yourself

**Comment by JadeMin** [comment]
Please update to the latest commit. It looks like your code is out of date.

**Comment by Qaveru** [comment]
it worked but now I have a new issue #10
